/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pos;

/**
 *
 * @author Chinthaka Prasad
 */
public class ViewReportsForm extends javax.swing.JFrame {

    /**
     * Creates new form ViewReportsForm
     */
    public ViewReportsForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        viewCustomerBtn = new javax.swing.JButton();
        allCustomerBtn = new javax.swing.JButton();
        bestInCustomerBtn = new javax.swing.JButton();
        categorizedByQtyBtn = new javax.swing.JButton();
        categorizedByAmountBtn = new javax.swing.JButton();
        ordersByAmountBtn = new javax.swing.JButton();
        allOrdersBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Reports");

        backBtn.setBackground(new java.awt.Color(255, 153, 153));
        backBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(51, 51, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Fashion Shop");
        jLabel7.setOpaque(true);

        viewCustomerBtn.setBackground(new java.awt.Color(51, 153, 0));
        viewCustomerBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewCustomerBtn.setText("View Customers");
        viewCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCustomerBtnActionPerformed(evt);
            }
        });

        allCustomerBtn.setBackground(new java.awt.Color(51, 153, 0));
        allCustomerBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        allCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        allCustomerBtn.setText("All Customers");
        allCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allCustomerBtnActionPerformed(evt);
            }
        });

        bestInCustomerBtn.setBackground(new java.awt.Color(51, 153, 0));
        bestInCustomerBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bestInCustomerBtn.setForeground(new java.awt.Color(255, 255, 255));
        bestInCustomerBtn.setText("Best In Customers");
        bestInCustomerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bestInCustomerBtnActionPerformed(evt);
            }
        });

        categorizedByQtyBtn.setBackground(new java.awt.Color(102, 102, 255));
        categorizedByQtyBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        categorizedByQtyBtn.setForeground(new java.awt.Color(255, 255, 255));
        categorizedByQtyBtn.setText("Categorized By QTY");
        categorizedByQtyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorizedByQtyBtnActionPerformed(evt);
            }
        });

        categorizedByAmountBtn.setBackground(new java.awt.Color(102, 102, 255));
        categorizedByAmountBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        categorizedByAmountBtn.setForeground(new java.awt.Color(255, 255, 255));
        categorizedByAmountBtn.setText("Categorized By Amount");
        categorizedByAmountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categorizedByAmountBtnActionPerformed(evt);
            }
        });

        ordersByAmountBtn.setBackground(new java.awt.Color(153, 153, 153));
        ordersByAmountBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ordersByAmountBtn.setForeground(new java.awt.Color(255, 255, 255));
        ordersByAmountBtn.setText("Orders By Amount");
        ordersByAmountBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ordersByAmountBtnActionPerformed(evt);
            }
        });

        allOrdersBtn.setBackground(new java.awt.Color(153, 153, 153));
        allOrdersBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        allOrdersBtn.setForeground(new java.awt.Color(255, 255, 255));
        allOrdersBtn.setText("All Orders");
        allOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allOrdersBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bestInCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(categorizedByAmountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                            .addComponent(categorizedByQtyBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ordersByAmountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(allOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(viewCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categorizedByQtyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ordersByAmountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(bestInCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categorizedByAmountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addComponent(allCustomerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 60, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void viewCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCustomerBtnActionPerformed
        // TODO add your handling code here:
        new ViewCustomerForm().setVisible(true);
    }//GEN-LAST:event_viewCustomerBtnActionPerformed

    private void bestInCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bestInCustomerBtnActionPerformed
        // TODO add your handling code here:
        new BestInCustomerForm().setVisible(true);
    }//GEN-LAST:event_bestInCustomerBtnActionPerformed

    private void allCustomerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allCustomerBtnActionPerformed
        // TODO add your handling code here:
        new AllCustomerForm().setVisible(true);
    }//GEN-LAST:event_allCustomerBtnActionPerformed

    private void categorizedByQtyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorizedByQtyBtnActionPerformed
        // TODO add your handling code here:
        new ItemsByQtyForm().setVisible(true);
    }//GEN-LAST:event_categorizedByQtyBtnActionPerformed

    private void categorizedByAmountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categorizedByAmountBtnActionPerformed
        // TODO add your handling code here:
        new ItemsByAmountForm().setVisible(true);
    }//GEN-LAST:event_categorizedByAmountBtnActionPerformed

    private void ordersByAmountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ordersByAmountBtnActionPerformed
        // TODO add your handling code here:
        new OrderByAmountForm().setVisible(true);
    }//GEN-LAST:event_ordersByAmountBtnActionPerformed

    private void allOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allOrdersBtnActionPerformed
        // TODO add your handling code here:
        new AllOrdersForm().setVisible(true);
    }//GEN-LAST:event_allOrdersBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReportsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReportsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allCustomerBtn;
    private javax.swing.JButton allOrdersBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bestInCustomerBtn;
    private javax.swing.JButton categorizedByAmountBtn;
    private javax.swing.JButton categorizedByQtyBtn;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton ordersByAmountBtn;
    private javax.swing.JButton viewCustomerBtn;
    // End of variables declaration//GEN-END:variables
}
